[build]
  base = "client"
  publish = "build"
  command = "npm install && GENERATE_SOURCEMAP=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"
  TSC_COMPILE_ON_ERROR = "true"
  ESLINT_NO_DEV_ERRORS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
